name: kayan_news
description: تطبيق إخباري عربي احترافي للأخبار المحلية والعربية والعالمية.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  xml: ^6.6.1
  url_launcher: ^6.3.2
dependencies:
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
